export const events = {
  ALERT: "ALERT",
  REFETCH_CHATS: "REFETCH_CHATS",
  NEW_ATTACHMENT: "NEW_ATTACHMENT",
  NEW_MESSAGE_ALERT: "NEW_MESSAGE_ALERT",
  NEW_REQUEST: "NEW_REQUEST",
  NEW_MESSAGE: "NEW_MESSAGE",
  START_TYPING: "START_TYPING",
  STOP_TYPING: "STOP_TYPING",
  CHAT_JOINED: "CHAT_JOINED",
  CHAT_LEAVED: "CHAT_LEAVED",
  ONLINE_USERS: "ONLINE_USERS",
};
